version: "3"

networks:
    net-192.168.60.0:
        name: net-192.168.60.0
        ipam:
            config:
                - subnet: 192.168.60.0/24
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24

services:
    Router:
        image:  handsonsecurity/seed-ubuntu:large 
        container_name: router
        tty: true
        cap_add:
                - ALL
        sysctls:
                - net.ipv4.ip_forward=1
        networks:
            net-192.168.60.0:
                ipv4_address: 192.168.60.11
            net-10.9.0.0:
                ipv4_address: 10.9.0.11
        command: bash -c "
                      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE &&
                      iptables -A FORWARD -d 192.168.60.80 -j DROP  &&
                      tail -f /dev/null
                 "
               
    iot-server:
        image:  handsonsecurity/seed-server:flask 
        container_name: iot-server
        tty: true
        cap_add:
                - ALL
        volumes:
                - ./apps/smartBulb:/app/smartBulb
        networks:
            net-192.168.60.0:
                ipv4_address: 192.168.60.80
        command: bash -c "
                  FLASK_APP=/app/smartBulb flask run --host 0.0.0.0 --port 80
                 "
    attacker-web:
        image:  handsonsecurity/seed-server:flask 
        container_name: attacker-web
        tty: true
        cap_add:
                - ALL
        volumes:
                - ./apps/cmpt733attacker:/app/cmpt733attacker
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.180
        command: bash -c "
                  FLASK_APP=/app/cmpt733attacker flask run --host 0.0.0.0 --port 80
                 "
    attacker-ns:
        build: ./attacker_ns
        image: attacker-ns
        container_name: attacker-ns
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.153

    local-dns-server:
        build: ./local_dns_server
        image: local-dns-server
        container_name: local-dns-server
        tty: true
        cap_add:
                - ALL
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.53


